// <auto-generated />
using System;
using DarkPatterns.OneTimePassword.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DarkPatterns.OneTimePassword.Migrations
{
    [DbContext(typeof(OtpDbContext))]
    partial class OtpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DarkPatterns.OneTimePassword.Persistence.DeliveredOneTimePassword", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("MediumCode")
                        .HasColumnType("text");

                    b.Property<string>("DeliveryTarget")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("ApplicationId", "MediumCode", "DeliveryTarget");

                    b.ToTable("DeliveredPasswords");
                });
#pragma warning restore 612, 618
        }
    }
}
