openapi: "3.0.3"
info:
  version: 1.0.0
  title: One Time Password
  description: Simple and Secure one time password (OTP) API, by Dark Patterns Digital
paths:
  /env:
    summary: Gets the public API environment data
    get:
      operationId: getEnvironmentInfo
      summary: Gets the public API environment data
      responses:
        200:
          description:
            Contains public environment info that is still useful for developers
            when debugging issues
          content:
            application/json:
              schema:
                type: object
                required:
                  - gitHash
                  - tag
                properties:
                  gitHash:
                    description: Git commit hash
                    type: string
                  tag:
                    description: Build tag id
                    type: string
  /otp:
    post:
      operationId: sendOtp
      description: Send an OTP to a destination
      security:
        - LicensedApp: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                medium:
                  $ref: "#/components/schemas/Medium"
                destination: { type: string }
              required:
              - medium
              - destination
      responses:
        201:
          description: The OTP was delivered successfully
        400:
          description: The destination was invalid or could not be delivered to
  /otp/verify:
    post:
      operationId: verifyOtp
      description: Verify an OTP sent to a destination
      security:
        - LicensedApp: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                medium:
                  $ref: "#/components/schemas/Medium"
                destination: { type: string }
                otp: { type: string }
              required:
              - medium
              - destination
              - otp
      responses:
        200:
          description: The correct OTP was passed
        400:
          description: The destination was invalid
        409:
          description: The incorrect OTP was passed, or was not associated with the destination
components:
  schemas:
    Medium:
      type: string
      enum:
        - sms
        - email
        - voice
  securitySchemes:
    LicensedApp:
      type: apiKey
      in: header
      name: x-api-key